# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.14.0-chrome99-ff97

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Check submodules
      #- name: Check submodules
      #  run: git submodule update --init --recursive

      # Upload screenshots if failure
      - name: Upload screenshots if failure
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress-screenshots
      #    #working-directory: cypress

      # Upload videos if failure
      - name: Upload videos if failure
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-videos
          path: cypress-videos
      #    #working-directory: cypress

      - name: "show current directory and files"
        run: |
          pwd && mkdir screenshots && mkdir videos
          ls -al
          
      - name: "Install Cypress"
        run: npm install cypress --save-dev
        
      - name: "Cypress test"
        run: npx cypress run

        
      #- name: "Cypress Tests using Chrome"
      #  uses: cypress-io/github-action@v6
      #  with:
      #    start: yarn start
      #    #working-directory: cypress
      #    browser: chrome
      #    record: false
      #    parallel: false
      #    spec: |
      #      cypress/e2e/baidu_web/*

